version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - rm -rf node_modules         # 🧹 Clean before install
      - rm -f package-lock.json     # optional: clean lock file if issues continue
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build

